spring:
  application:
    name: eureka-service
  profiles:
      active: dev #默认启动环境
  http:
    encoding:
      #防止中文乱码
      force: true

eureka:
  client:
    #是否检索服务
    fetch-registry: true
    #是否向注册中心注册自己
    register-with-eureka: true
    #healthcheck:
    #  enabled: true   #开启健康检查

  instance:
    preferIpAddress: true  #使用IP而不是主机名注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

    #服务失效时间
    #lease-expiration-duration-in-seconds: 90
    #服务续约任务调用间隔时间 心跳
    #lease-renewal-interval-in-seconds: 30

security:
  basic:
    enabled: true #开启认证
    path: /   #针对全部路径进行认证

#对暴露的Endpoints进行权限校验，设置监控接口前缀
management:
  security:
    enabled: true
  #context-path: /monitor  #actuator暴露接口的前缀


